### ISSUE TITLE
`not` doesn't work correctly with set

### ISSUE THREAD

**Issue by fmnoise** [fmnoise/qb#3]
https://stackoverflow.com/questions/68529942/datomic-not-in-collection-query-is-not-working

**Comment by Aeonax** [comment]
From my side, I would prefer not to unwrap sets during passing arguments [qb/in](https://github.com/fmnoise/qb/blob/master/src/fmnoise/qb.clj#L24) and allow to pass binding as it is to use
```clj
(-> (find '[?o (sum ?a)])
    (in '?invalid-statuses #{cancelled :postponed})
    (where? '[?o :order/id ?id] order-id)
    (where* '[[?o :order/status ?o-status]
              (not [(contains? ?invalid-statuses ?o-status)])
              [?o :order/items ?i]
              [?i :item/amount ?a]]))
```
And then it will require `where-not` fixing 🌚  at least docs...

...

So from my side sets handling should be reviewed after this revelation... or workarounds found. Still, workarounds feel redundant to me - I already gave up on the idea to find a better solution than `contains?`😅 ... Unless this workaround will be on the level of `qb/where...` and for `qb/in` will be allowed to pass sets/binding as they are.
```clj
(-> ... (where '[?o :order/status ?status] #{...}))
;; same as
(-> ...
    (in [?status ...] #{...})
    (where '[?o :order/status ?status]))

;;; 😬 🤦‍♂️ 🙈 🙈 🙈 🙈 
(-> ... (where-not '[?o :order/status ?status] #{...}))
;; same as
(let [sym (gensym)]
  (-> ...
      (in sym #{...})
      (where* '[[?o :order/status ?status]
                (not [(contains? sym ?status)])])))
```

**Comment by fmnoise** [comment]
@Aeonax https://github.com/fmnoise/qb/pull/4
I've added 2 low-level functions 
- `add-input` for adding raw input with option to auto-expand collection
- `exclude` which filters out values from supplied set (or other collection)

**Comment by fmnoise** [comment]
I ended up with using set instead of `contains?` after some benchmarking, set seems to be twice more performant
you can try it as well

```clj
(defn benchmark [size times func]
  (let [s (set (range size))]
    (->> (func s n)
         (dotimes [n times])
         time
         with-out-str
         (re-find #"\d+.\d+")
         Double/parseDouble)))
